pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('reviews/',include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
# URL설정을 app 단위로!
from django.urls import path 
from .views import create_views, detail_views, index_views, comment_views

app_name = 'reviews'

urlpatterns = [
  path('', index_views.index, name='index'),
  path('create/', create_views.create, name='create'),
  path('<int:pk>/update/', create_views.update, name='update'),
  path('<int:pk>/', detail_views.detail, name='detail'),
  path('<int:pk>/delete', detail_views.delete, name='delete'),
  path('<int:pk>/comments/', comment_views.comment_create, name='comment_create'),
  path('<int:pk>/comments/<int:comment_pk>/delete/', comment_views.comments_delete, name='comments_delete'),
]

reviews/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.

class Reviews(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    movie_name = models.CharField(max_length=100)
    grade = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Reviews, on_delete=models.CASCADE)
    content = models.TextField()

reviews/forms.py
from django import forms
from .models import Comment, Reviews

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Reviews
        fields = ['title', 'content', 'movie_name', 'grade','image']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment 
        fields = ['content',]

reviews/views/comment_views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from ..models import Reviews,Comment
from ..forms import ReviewForm, CommentForm

def comment_create(request, pk):
    review = Reviews.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect('reviews:detail', review.pk)

def comments_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if  request.user == comment.user: 
        comment.delete()
    else:
        messages.error(request,'삭제안대!!')
    return redirect('reviews:detail', pk)

reviews/views/create_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from reviews.models import Reviews
from ..forms import ReviewForm
@login_required
def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('reviews:index')
    else: 
        review_form = ReviewForm()
    context = {
        'review_form': review_form
    }
    return render(request, 'reviews/form.html', context=context)

@login_required
def update(request, pk):
    review = Reviews.objects.get(pk=pk)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES, instance=review)
        if review_form.is_valid():
            review_form.save()
            messages.success(request, '글이 수정되었습니다.')
            return redirect('reviews:detail', review.pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        'review_form': review_form
    }
    return render(request, 'reviews/form.html', context)

reviews/views/detail_views.py
from django.shortcuts import render
from ..models import Reviews
from django.shortcuts import render, redirect
from ..forms import CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def detail(request, pk):
    review = Reviews.objects.get(pk=pk)
    comment_form = CommentForm()
    context ={
        'review': review,
        'comments' : review.comment_set.all(),
        'comment_form': comment_form
    }
    return render(request, 'reviews/detail.html',context)

@login_required
def delete(request, pk):
    review = Reviews.objects.get(pk=pk)
    if request.user == review.user:
        review.delete()
    return redirect('reviews:index')

reviews/views/index_views.py
from django.shortcuts import render, redirect
from ..models import Reviews

def index(request):
    reviews=Reviews.objects.all()
    return render(request,'reviews/index.html',{'reviews':reviews})

reviews/templates/reviews/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}

<h1>{{ review.title }}</h1>
<h3>{{ review.content }}</h3>
{% if request.user.is_authenticated %}
<a href="{% url 'reviews:update' review.pk %}" class="btn btn-outline-primary my-3">바꿀래</a>
{% endif %}
<a href="{% url 'reviews:index'%}" class="btn btn-outline-primary my-3">나갈래</a>
{% if request.user.is_authenticated %}
<a href="{% url 'reviews:delete' review.pk %}" class="btn btn-outline-danger my-3">지울래</a>
{% endif %}
<br>
<h4 class="my-3">댓글</h4>
<form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form layout='inline'%}
    <br>
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
<hr>
{% for comment in comments %}
<div>
    <ul class="d-flex justify-content-between">
        <li>{{comment.user}}&nbsp|&nbsp{{ comment.content }}
        </li>
        <a href="{% url 'reviews:comments_delete' review.pk comment.pk %}" class="btn btn-outline-danger my-3">삭제</a>
    </ul>
</div>

<hr>
{% empty %}
<p>댓글이 없어요 ㅠ_ㅠ</p>
{% endfor %}

<hr>
{% endblock %}

reviews/templates/reviews/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

{% if request.resolver_match.url_name == 'create' %}
<h1> 글쓰기 </h1>
{% else %}
<h1> 수정하기 </h1>
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% block content %}

<br>
{% for review in reviews %}

<a href="{% url 'reviews:detail' review.pk %}">{{review.title}}</a>
<form action="">

</form>
<div class="row">
    {% for review in reviews %}
    <div class="col-4 my-3">
      <div class="card">
        {% if review.image %}
          <img src="{{ review.image.url }}" class="card-img-top" alt="...">
        {% else %}
          <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ review.title }}</h5>
          <a href="{% url 'reviews:detail' review.pk %}" class="btn btn-outline-primary my-3">상세보기</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endfor %}
{% endblock %}