accounts/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path
from .views import login_views,signup_views
app_name = "accounts"
urlpatterns = [
    # signup_views
    path("signup/", signup_views.signup, name="signup"),
    # login_views
    path('login/', login_views.login, name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', login_views.logout, name='logout'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('reviews/',include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
# URL설정을 app 단위로!
from django.urls import path 
from .views import create_views, detail_views, index_views, comment_views

app_name = 'reviews'

urlpatterns = [
  path('', index_views.index, name='index'),
  path('create/', create_views.create, name='create'),
  path('<int:pk>/update/', create_views.update, name='update'),
  path('<int:pk>/', detail_views.detail, name='detail'),
  path('<int:pk>/delete', detail_views.delete, name='delete'),
  path('<int:pk>/comments/', comment_views.comment_create, name='comment_create'),
  path('<int:pk>/comments/<int:comment_pk>/delete/', comment_views.comments_delete, name='comments_delete'),
]

pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Document</title>
</head>


<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

pjt/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="#">PJT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'reviews:index' %}">Home</a>
          </li>
              {% if request.user.is_authenticated %}
              {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user }}</a>
              </li> {% endcomment %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup'%}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'reviews:create' %}">글 쓰기</a>
            {% endif %}
        </ul>
      </div>
    </div>
</nav>